# -*- coding: utf-8 -*-
"""nirs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eILGnJ0fDl28xaFGefl3ZQ-jnC5OARmJ
"""

from google.colab import drive
drive.mount('/content/drive')

import json
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from google.colab.patches import cv2_imshow
file_path = '/content/drive/My Drive/Slide_detection.v1i.coco/'

from pycocotools.coco import COCO
import matplotlib.pyplot as plt
import cv2

# Путь к файлу аннотаций

ann_train = file_path + 'train/_annotations.coco.json'
coco_train = COCO(ann_train)

ann_valid = file_path + 'valid/_annotations.coco.json'
coco_valid = COCO(ann_valid)

ann_test = file_path + 'test/_annotations.coco.json'
coco_test = COCO(ann_test)


categories = coco_train.loadCats(coco_train.getCatIds())
print(categories)

def data_generator(coco, file_path, cat_ids,  target_size, batch_size=8):
    img_ids = coco.getImgIds(catIds=cat_ids)
    imgs = coco.loadImgs(img_ids) #

    while True:
        images = []
        bboxes = []
        for img_info in imgs:
            try:
                # Загружаем изображение
                img_name = file_path + img_info['file_name']
                img = cv2.imread(img_name)
                if img is None:
                    print("Error loading image")
                    continue
                img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

                # Извлекаем bounding box
                ann_ids = coco.getAnnIds(imgIds=img_info['id'], catIds=cat_ids, iscrowd=False)
                annotations = coco.loadAnns(ann_ids)

                if len(annotations) == 0:
                    continue

                ann = annotations[0]  # Берем первую аннотацию (если их несколько, можно модифицировать)
                x, y, w, h = ann['bbox']

                # Подгонка изображения под нужный размер
                img_gray = cv2.resize(img_gray, target_size)
                img_gray = np.expand_dims(img_gray, axis=-1)

                # Нормализуем координаты bbox относительно размеров изображения
                img_h, img_w = img_info['height'], img_info['width']
                bbox = [x / img_w, y / img_h, w / img_w, h / img_h]

                images.append(img_gray)
                bboxes.append(bbox)

                if len(images) == batch_size:
                    yield (np.array(images), np.array(bboxes))
                    images = []
                    bboxes = []

            except Exception as e:
                print(f"Error processing image {img_info['file_name']}: {e}")
                continue

        if len(images) > 0:
            yield (np.array(images), np.array(bboxes))
            images = []
            bboxes = []

train_ids = coco_train.getCatIds(catNms=['projection screen'])
valid_ids = coco_valid.getCatIds(catNms=['projection screen'])
test_ids = coco_test.getCatIds(catNms=['projection screen'])

train_img_ids = coco_train.getImgIds(catIds=train_ids)
train_images = coco_train.loadImgs(train_img_ids)
print("train", len(train_images))
valid_img_ids = coco_valid.getImgIds(catIds=valid_ids)
valid_images = coco_valid.loadImgs(valid_img_ids)
print("valid", len(valid_images))
test_img_ids = coco_test.getImgIds(catIds=test_ids)
test_images = coco_test.loadImgs(test_img_ids)
print("test", len(test_images))

import tensorflow as tf

# Проверка наличия доступных GPU
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("Доступные GPU:", gpus)
else:
    print("GPU не обнаружено. Убедитесь, что CUDA и cuDNN установлены.")

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
checkpoint_path = "/content/drive/MyDrive/checkpoints/cp-{epoch:04d}.weights.h5"

checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_path,   # путь для сохранения
    save_weights_only=True,     # сохранять только веса, без архитектуры
    monitor='val_loss',         # метрика для мониторинга (например, ошибка на валидации)
    save_best_only=True,        # сохранять только лучшую модель (с минимальной потерей)
    verbose=1                   # выводить информацию о сохранении
)
def build_model(input_shape):
    inputs = tf.keras.Input(shape=input_shape)

    # Блок сверток с BatchNormalization и Dropout
    x = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = tf.keras.layers.Dropout(0.3)(x)  # Регуляризация

    x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = tf.keras.layers.Dropout(0.3)(x)

    x = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = tf.keras.layers.Dropout(0.3)(x)

    x = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = tf.keras.layers.Dropout(0.3)(x)

    # Развертывание в плоский вектор
    x = tf.keras.layers.Flatten()(x)

    # Полносвязный слой
    x = tf.keras.layers.Dense(256, activation='relu')(x)  # Увеличение нейронов в слое
    x = tf.keras.layers.Dropout(0.5)(x)  # Регуляризация

    # Финальный слой предсказания 4 координат (x, y, ширина, высота)
    output = tf.keras.layers.Dense(4, activation='linear')(x)

    # Создание модели
    model = tf.keras.Model(inputs=inputs, outputs=output)

    return model

early_stop = EarlyStopping(monitor='val_iou_metric', patience=5, restore_best_weights=True, mode="max")

"""от 5 до 100, чем больше

"""

batch_size = 32
total_steps = len(coco_train.getImgIds(catIds=train_ids)) // batch_size
# Генератор для загрузки данных
target_size = (64,64)
train_data_gen = data_generator(coco_train, '/content/drive/My Drive/Slide_detection.v1i.coco/train/', train_ids,target_size, batch_size=batch_size)

valid_data_gen = data_generator(coco_valid,  '/content/drive/My Drive/Slide_detection.v1i.coco/valid/',valid_ids,target_size, batch_size=batch_size )

test_data_gen = data_generator(coco_test, '/content/drive/My Drive/Slide_detection.v1i.coco/test/', test_ids,target_size, batch_size=batch_size )

from tensorflow.keras.saving import register_keras_serializable

# Регистрируем функцию как сериализуемую
@register_keras_serializable()
def iou_metric(output_true, output_pred):
    output_true = tf.cast(output_true, tf.float32)
    output_pred = tf.cast(output_pred, tf.float32)
    # Разбиваем координаты рамок на (x, y, width, height)
    x_true, y_true, w_true, h_true = tf.split(output_true, 4, axis=-1)
    x_pred, y_pred, w_pred, h_pred = tf.split(output_pred, 4, axis=-1)

    x_left = tf.maximum(x_true, x_pred)
    y_top = tf.maximum(y_true, y_pred)
    x_right = tf.minimum(x_true + w_true, x_pred + w_pred)
    y_bottom = tf.minimum(y_true + h_true, y_pred + h_pred)

    # Вычисляем площадь пересечения
    intersection = tf.maximum(0.0, x_right - x_left) * tf.maximum(0.0, y_bottom - y_top)
    # Площадь объединения
    union = (w_true * h_true) + (w_pred * h_pred) - intersection
    # Предотвращение деления на ноль
    return tf.reduce_mean(intersection / (union + tf.keras.backend.epsilon()))


def scheduler(epoch, lr):
    if epoch < 10:
        return lr  # Поддерживаем начальную скорость обучения
    else:
        return float(lr * tf.math.exp(-0.1))  # Уменьшаем learning rate по экспоненциальному закону
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
lr_scheduler = tf.keras.callbacks.LearningRateScheduler(scheduler, verbose=1)

"""iou реализовать вручную из координат

"""

# input_shape = (320, 320, 1)  # Размеры изображения: ширина, высота, каналы (RGB)
# model = build_model(input_shape)
# with tf.device('/GPU:0'):
#     model = build_model(input_shape)  # Пример входного размера
#     # Компиляция модели с IoU в качестве метрики
#     model.compile(optimizer=optimizer, loss='mse', metrics=[iou_metric])

# # Вывод структуры модели
# model.summary()

# history = model.fit(
#     train_data_gen,
#     steps_per_epoch=total_steps,
#     epochs=50,
#     validation_data=valid_data_gen,
#     validation_steps=53,
#     callbacks=[early_stop, lr_scheduler]
# )

# Сохранение модели
# model.save('/content/drive/MyDrive/НИРС/model_2207.keras')

# model.save('/content/drive/MyDrive/НИРС/model_2223.keras')

new_model = tf.keras.models.load_model('/content/drive/MyDrive/НИРС/model_2223.keras')
new_model.summary()

new_model = tf.keras.models.load_model('/content/drive/MyDrive/my_model.keras')
print("Starting evaluation...")
new_test_data_gen = data_generator(coco_test, '/content/drive/My Drive/Slide_detection.v1i.coco/test/', test_ids,(64,64), batch_size=batch_size )
loss, acc = new_model.evaluate(new_test_data_gen, verbose=2, steps=27)

new_model.summary()

import random
target_size = (64,64)
def get_aspect_ratio(rect):
  w, h = rect[0], rect[1]  # Ширина и высота
  return max(w/h, h/w)

def calculate_iou():
  img_id_rand = random.choice(test_img_ids)
  img_info = coco_test.loadImgs(img_id_rand)
  path = '/content/drive/MyDrive/Slide_detection.v1i.coco/test/' + img_info[0]['file_name']

  print(path)
  image_gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
  ann = coco_test.loadAnns(img_id_rand)
  ground_truth = ann[0]['bbox']

  # Изменение размера изображения
  image_resized = cv2.resize(image_gray, target_size)
  image_ready = np.expand_dims(image_resized, axis=-1)  # Добавляем канал (для черно-белого)
  image_ready = np.expand_dims(image_ready, axis=0)  # Добавляем размер batch
  output_image = cv2.cvtColor(image_gray, cv2.COLOR_GRAY2BGR)
  ### Model
  # Получите координаты слайда
  model_coordinates = new_model.predict(image_ready)
  # Выведите результат
  print("Predicted coordinates:", model_coordinates)


  #### CANNY
  blurred_image = cv2.GaussianBlur(image_gray, (5, 5), 1.9)

  # 2. Расчет градиентов изображения с помощью Canny
  edges = cv2.Canny(blurred_image, threshold1=50, threshold2=150)

  # 6. Математическая морфология
  # Операция расширения (для увеличения толщины границ)
  kernel = np.ones((5, 5), np.uint8)  # Создание ядра для морфологии
  dilated_edges = cv2.dilate(edges, kernel, iterations=1)

  # Исходное изображение
  contours, _ = cv2.findContours(dilated_edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

  # Параметры для отсечения пропорций экрана
  min_aspect_ratio = 2/3
  max_aspect_ratio = 16/9

  # Переменная для хранения прямоугольников экрана
  screen_rects = []

  # Проходим по всем контурам
  for contour in contours:
      # Аппроксимация контура до прямоугольника
      rect = cv2.minAreaRect(contour)
      box = cv2.boxPoints(rect)  # Получаем 4 точки прямоугольника
      box = np.intp(box)
      # Вычисляем соотношение сторон
      aspect_ratio = get_aspect_ratio(rect[1])
      min_area_threshold = 70000
      max_area_threshold = 200000

      # Проверяем, соответствует ли соотношение сторон экрана
      if min_aspect_ratio <= aspect_ratio <= max_aspect_ratio:
          area = cv2.contourArea(box)
          # Если площадь больше порога, добавляем прямоугольник
          if max_area_threshold >  area > min_area_threshold:
              screen_rects.append(box)

  canny_prediction = [0,0,0,0]
  if screen_rects:
      # Функция для вычисления площади прямоугольника
      def rect_area(rect):
          # Используем cv2.contourArea, чтобы вычислить площадь
          return cv2.contourArea(rect)

      # Находим прямоугольник с максимальной площадью
      max_rect = max(screen_rects, key=rect_area)

      # Отображаем его на изображении (для наглядности)
      # cv2.polylines(output_image, [max_rect], isClosed=True, color=(255, 0, 0), thickness=3)
      x, y, w, h = cv2.boundingRect(max_rect)
      canny_prediction = [x, y, w, h]
      print("Canny prediction:", canny_prediction)


  else:
      print("Список screen_rects пуст.")

  # Извлекаем координаты bbox
  x1, y1, width, height = [int( i*640 ) for i in model_coordinates[0]]
  print(x1, y1, width, height )
  width = min(width, 640 - x1)
  height = min(height, 640 - y1)
  predicted = [x1, y1, width, height]
  ground_truth = [int(i) for i in ground_truth]


  # Рисуем истинный bbox (зеленый)
  cv2.rectangle(output_image,
                (ground_truth[0], ground_truth[1]),
                (ground_truth[0] + ground_truth[2], ground_truth[1] + ground_truth[3]),
                (0, 255, 0), 2)  # зеленый цвет (BGR)

  # Рисуем предсказанный bbox (голубой)
  cv2.rectangle(output_image,
                (predicted[0], predicted[1]),
                (predicted[0] + predicted[2], predicted[1] + predicted[3]),
                (255, 255, 0), 2)  # голубой цвет (BGR)
  # Рисуем детектированный bbox (красный)
  cv2.rectangle(output_image,
                (canny_prediction[0], canny_prediction[1]),
                (canny_prediction[0] + canny_prediction[2], canny_prediction[1] + canny_prediction[3]),
                (0, 0, 255), 2)  # Красный цвет (BGR)

  # Рассчитываем IoU
  iou_model = iou_metric(ground_truth, predicted)
  iou_canny = iou_metric(ground_truth, canny_prediction)

  # Добавляем текст IoU на изображение
  text = f"IoU_model: {iou_model:.2f}"
  cv2.putText(output_image, text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1,  (255, 255, 0), 2)
  text = f"IoU_canny: {iou_canny:.2f}"
  cv2.putText(output_image, text, (10, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

  # Отображаем изображение
  plt.figure(figsize=(8, 8))
  plt.imshow(cv2.cvtColor(output_image, cv2.COLOR_BGR2RGB))  # Преобразование BGR в RGB для отображения
  plt.title("Сравнение методов")
  plt.axis('off')
  plt.show()

calculate_iou()

